In [ ]:
import pandas as pd

# Replace the Google Sheets document ID and sheet name in the URL
document_id = '1rlP9mSfvJE73xK6Q5ddtDnk67U6D1DjVsJH-1dIXOXk'
sheet_name = 'matches'  # Replace with the appropriate sheet name or index if necessary
url = f'https://docs.google.com/spreadsheets/d/{document_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

# Read the Google Sheets document into a DataFrame
test = pd.read_csv(url,
                   index_col=0,  # Set first column as rownames in DataFrame
                   parse_dates=['match_date']  # Parse column values to datetime
                  )

test.head(5)

In [ ]:
test[['tournament_id', 'stage', 'home_team_name', 'away_team_name', 'home_team_score', 'away_team_score']]

In [5]:
import pandas as pd
document_id = '1rlP9mSfvJE73xK6Q5ddtDnk67U6D1DjVsJH-1dIXOXk'
sheet_name = 'All-Time-Results'  # Replace with the appropriate sheet name or index if necessary
url = f'https://docs.google.com/spreadsheets/d/{document_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

test = pd.read_csv(url,
                   index_col=0,  # Set first column as rownames in DataFrame
#                    parse_dates=['match_date']  # Parse column values to datetime
                  )

test.head(5)

,home,away,home_goal,away_goal,home_result,away_result,H Win,H Draw,H Loss,A Win,A Draw,A Loss
season,,,,,,,,,,,,
2002/2003,Jigawa Golden Stars,Bendel Insurance,1.0,0.0,H Win,A Loss,Jigawa Golden Stars,NaN,NaN,NaN,NaN,Bendel Insurance
2002/2003,Wikki Tourists,Sunshine Stars,1.0,1.0,H Draw,A Draw,NaN,Wikki Tourists,NaN,NaN,Sunshine Stars,NaN
2002/2003,Kwara United,Kano Pillars,4.0,2.0,H Win,A Loss,Kwara United,NaN,NaN,NaN,NaN,Kano Pillars
2002/2003,Julius Berger,Gombe United,3.0,0.0,H Win,A Loss,Julius Berger,NaN,NaN,NaN,NaN,Gombe United
2002/2003,Plateau United,Dolphin,1.0,0.0,H Win,A Loss,Plateau United,NaN,NaN,NaN,NaN,Dolphin

In [7]:
test.shape

(7206, 12)